### ISSUE TITLE
Make an awesome Readme

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/hasselhoffme#10]
Hi

Since this project begins to be widely used, there is a need for a README that perfectly describes the purpose of this project. 

To remember, this project was born out of the need to raise awareness among co-workers who leave their computers unlocked. 

That's when, with a url that's easy enough to remember, you can open any console and put hass on your partner's desktop. 

The readme has to contain several winks and must make me laugh.

Thanks!

**Comment by mainakpal08** [comment]
Hi! can I try this one ?

**Comment by angelbarrera92** [comment]
Hi @mpalrocks . Only if you have been tested the functionality!

**Comment by ghost** [comment]
Tested under **Ubuntu 18.04 works**.. took a pretty while till it changed my default background scared to death...  Do I need to anything special to uninstall or remove it?

**Comment by angelbarrera92** [comment]
Hi @nfuhs 
You dont need nothing else a new awesome wallpaper. 
This binary only changes the wallpaper once. So, to revert this wallpaper, changes to another one as usual.

**Comment by ghost** [comment]
Thanks!

**Comment by angelbarrera92** [comment]
Done by #13
