### ISSUE TITLE
Make a windows script as linux ones

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/hasselhoffme#11]
This project needs an automatic script, like the one that works for linux and mac, to make it easier to run on windows operating systems. 

As you can see, in linux and macos operating systems, with a simple command you can download and run the binary. 
```bash
curl -L http://tiny.cc/hasselhoff | bash
```
As a requirement must be a single command line and that the procedure is as fast as possible. This must be documented in the README.md. 

It must be compatible with Windows 7 or later.

**Comment by guumaster** [comment]
By default Windows don't provide curl and doing it as a single command line would be hard. What if I try to create an `.exe` file that you can download and execute to set a random wallpaper? 

You'd just need to download it and execute it. Acceptable?

**Comment by angelbarrera92** [comment]
It has to be as simple as posible. So, you can try it ;)
