### ISSUE TITLE
Detect environments without graphical interface

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/hasselhoffme#15]
To remember, this software sets the wallpaper to a wonderful David Hasselhoff photo. 
But... What about desktop-less environments?

I'd like... in non-graphic environments, to set a message in `/etc/motd` *(linux and mac)* indicating the logged in user, the time this software was run along with a picture of David Hasselhoff in ASCII. 

The photo must be changing, like wallpapers, randomly. 

It must be developed in Golang or ShellScript.

**Comment by bengentil** [comment]
I've sent a PR (#16 )

it should work on all systems that uses "update-motd", however It could be easily adapted to generate a static /etc/motd if "update-motd" is not found
