### ISSUE TITLE
Adds contributors file

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/hasselhoffme#17]
This repository contains the contributions of several people. That makes me happy a lot and I would love to have a contributor file where the names of the contributors who have participated in this project. 

You can also add yourself as a contributor. 

I only accept pull requests that contain the full list of all contributors having a **funny differential touch**. 

Another requirements is to have linked the README.md with the new CONTRIBUTORS.md file. 

Thanks

**Comment by Mkelsey25** [comment]
Is this still open? I would like to contribute!

**Comment by angelbarrera92** [comment]
Yes. Take It!!

**Comment by Mkelsey25** [comment]
By "funny differential touch", do you mean you want me to come up with funny descriptions of what each contributor did?

**Comment by angelbarrera92** [comment]
Yes, why not???

**Comment by Mkelsey25** [comment]
Sounds like a plan!

**Comment by angelbarrera92** [comment]
Its a funny project!!

**Comment by Mkelsey25** [comment]
Submitted! This project is the best!!

**Comment by angelbarrera92** [comment]
![Hoff](https://tinypng.com/web/output/ycf4dr5jbmmyerzdt6hvhkc0u1k7rcr9/hoff.jpg)
Hoff approves
