### ISSUE TITLE
Add arm support

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/hasselhoffme#18]
This project is executed by [`hasselhoff.sh`](https://github.com/angelbarrera92/hasselhoffme/blob/0.2.1/hasselhoff.sh) script.

This script does not take care about os architecture. So, executing this on a raspberry pi to test #16 does not works:

```bash
line 22: /tmp/david/hasselhoffme_0.2.1_linux_amd64: cannot execute binary file: Exec format errorz
```

Travis generates a linux arm version that is available at [releases section](https://github.com/angelbarrera92/hasselhoffme/releases). You have to modify hasselhoff.sh script to add some intelligence to detect processor architecture. 

Thanks

**Comment by yulrizka** [comment]
Cool project. was going to build something like this for kid with my co worker. #20 is my attempt for it
