### ISSUE TITLE
Develop this marvellous tool in Python or Go

### ISSUE THREAD

**Issue by ervitis** [angelbarrera92/hasselhoffme#2]
Use python or Go for developing this tool

Glory to Hasselhof!

**Comment by angelbarrera92** [comment]
Yes. That could be a good approach.
How would you design the solution to invoke a single API and get the correct binary? 

Windows, Linux and MacOS needs different binary files.

**Comment by ervitis** [comment]
I have read this article http://blog.questionable.services/article/build-go-binaries-travis-ci-github/ So you can compile for any platform

**Comment by angelbarrera92** [comment]
Yes mate. That is the easy part. How about download the correct binary from
a single uri?

You know, a script could be Cross plataform, at leader between MacOS and
Linux.

**Comment by ervitis** [comment]
Why you need to do that part instead let the user choose which platform is using?

**Comment by angelbarrera92** [comment]
Finished the development in go. All the pieces are still to be linked.
