### ISSUE TITLE
Mac OS - Second Screen

### ISSUE THREAD

**Issue by paurosello** [angelbarrera92/hasselhoffme#21]
Only changes background on main screen

**Comment by angelbarrera92** [comment]
I dont know if this applies in this repository. We are using a third party golang library: https://github.com/reujab/wallpaper
So, we have to investigate if we can use this library with some options to solve this issue, or open a new issue to @reujab: https://github.com/reujab/wallpaper

**Comment by reujab** [comment]
@paurosello The library uses AppleScript to set the wallpaper, but I don't have instant access to a Mac, so can you run the following command in a terminal and tell me if it sets the background of every desktop?
```sh
osascript -e 'tell application "System Events" to tell every desktop to set picture to POSIX file "/Library/Desktop Pictures/Desert.jpg"
```

**Comment by paurosello** [comment]
It works after accepting the following popup in Mojave :)

![image](https://user-images.githubusercontent.com/1133954/47483760-4c068a80-d83a-11e8-89d4-544a81a98b4d.png)

**Comment by reujab** [comment]
If you replace `System Events` with `Finder`, does it display the same popup?

**Comment by paurosello** [comment]
Tried this and other solution like:

```
tell application "Finder"
	set theDesktops to a reference to every desktop
	set picture of desktop of the theDesktops to POSIX file "/Library/Desktop Pictures/Desert 3.jpg"
end tell
```

with no luck, cannot seem to do it with finder for both screens, only with Sytem Events

**Comment by reujab** [comment]
The popup is undesirable, so I will not make `System Events` the default behavior of my library.

@angelbarrera92 What behavior do you want? Do you want your application to always display this popup, regardless of whether the user has multiple desktops?

EDIT: pinged wrong person

**Comment by angelbarrera92** [comment]
I did not see this message before, sorry.

We can assume click on a modal button if we can put hoff in all MacOS screens.

Thanks @reujab
