### ISSUE TITLE
Migrate to `go mod`

### ISSUE THREAD

**Issue by iknite** [angelbarrera92/hasselhoffme#25]
Since 1.11 go modules, it's included and the recommended package manager.

You can enable it by  setting a environment variable `GO111MODULE=on` and running `go mod why` it should create everything for you.

**Comment by angelbarrera92** [comment]
@iknite can you do it? with this issue you can participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by angelbarrera92** [comment]
@ervitis ?

**Comment by iknite** [comment]
for travis you should check the QED project for inspiration and :awesomeness: https://github.com/BBVA/qed/blob/master/.travis.yml#L33

**Comment by ervitis** [comment]
@angelbarrera92 what do you want?
