### ISSUE TITLE
Include go report in the README.md

### ISSUE THREAD

**Issue by iknite** [angelbarrera92/hasselhoffme#28]
https://goreportcard.com/report/github.com/angelbarrera92/hasselhoffme 

As it shows, it needs some love in the linting, license and the fmt areas.

**Comment by BigOokie** [comment]
This should be fixed by the PR #32 and improved with PR #33 to add a Makefile and fix the limiting issues.

**Comment by angelbarrera92** [comment]
Goreport added by @BigOokie in #32
