### ISSUE TITLE
panic: Could not load any image

### ISSUE THREAD

**Issue by jesmg** [angelbarrera92/hasselhoffme#44]
Trying to hasselhoff myself on Fedora, I got the following error:

curl -L https://tiny.cc/hasselhoffme | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   958  100   958    0     0   1362      0 --:--:-- --:--:-- --:--:--  1362
panic: Could not load any image

goroutine 1 [running]:
github.com/angelbarrera92/hasselhoffme/internal/images.SearchGithubRawImages(0x0, 0x0, 0x405600, 0xc000022118)
	/home/travis/gopath/src/github.com/angelbarrera92/hasselhoffme/internal/images/gitraw_images.go:36 +0x2a0
main.SearchRandomImage(0x745cd0, 0x0, 0x0, 0xc00004df88, 0xc000022118)
	/home/travis/gopath/src/github.com/angelbarrera92/hasselhoffme/cmd/hasselhoffme/hasselhoffme.go:51 +0x3a
main.main()
	/home/travis/gopath/src/github.com/angelbarrera92/hasselhoffme/cmd/hasselhoffme/hasselhoffme.go:34 +0x39

**Comment by angelbarrera92** [comment]
Should be fixed with the new 0.4.0 release

**Comment by angelbarrera92** [comment]
Feel free to re-open if it doesn't (2 years later)
