### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/hasselhoffme#9]
Since last change on `hasselhoff.sh` it stopped working on MacOS.

**Comment by angelbarrera92** [comment]
@dawud ¿?

**Comment by dawud** [comment]
Yeah, MacOS does not have `/dev/shm`, so fallback to `/tmp` on MacOS it is. I'll send a PR.

**Comment by angelbarrera92** [comment]
Reverted your merge. 
```bash
$ git reset HEAD^
$ git push origin +HEAD
```
